package ch.bfh.bti3001.snailsweeper.model;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class GridTest {
	
	@Test
	void testLostGame() {
		Grid grid;
		Grid nextGrid;
		GridSerializer serializer = new GridSerializer();
		
//
		String str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EH EH EH EH EH EH EH EH EH EH EH EH EH SV | SV LH EH EH EH EH EH EH EH EH EH EH EH EH EH LH EH EH EH SV | SV EH EH EH LH EH EH EH EH EH EH EH EH EH EH EH EH LH EH SV | SV EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH LH EH EH SV | SV EH EH LH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH SV | SV EH LH LH EH EH EH EH LH LH EH EH EH EH EH EH EH EH EH SV | SV LH EH EH EH EH EH EH LH EH EH EH EH EH EH EH EH EH EH SV | SV EH EH LH EH EH EH EH EH EH LH EH EH EH EH EH EH LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		grid = serializer.deserialize(str);
		
		grid.uncover(7, 4);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EV EV EV EV EV EV EV EV EV EH EH EH EH SV | SV LH EH EH EH EH EV EV EV EV EV EV EV EV EV LH EH EH EH SV | SV EH EH EH LH EV EV EV EV EV EV EV EV EV EV EH EH LH EH SV | SV EH EH EH EH EV EV EV EV EV EV EV EV EV EV EV LH EH EV SV | SV EH EH LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH LH LH EV EV EV EV LH LH EV EV EV EV EV EV EV EV EV SV | SV LH EH EH EV EV EV EV LH EH EH EV EV EV EV EV EV EV EV SV | SV EH EH LH EV EV EV EV EH EH LH EV EV EV EV EV EV LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		//___________________________
		//CHECK IN SOLUTION!!!
//		System.out.println("Uncovered");
		serializer.serialize(grid);
//		System.out.println("To Reach");
		serializer.serialize(nextGrid);
		//___________________________
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;
//
		grid.uncover(5, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EV EV EV EV EV EV EV EV EV EH EH EH EH SV | SV LH EH EH EH EV EV EV EV EV EV EV EV EV EV LH EH EH EH SV | SV EH EH EH LH EV EV EV EV EV EV EV EV EV EV EH EH LH EH SV | SV EH EH EH EH EV EV EV EV EV EV EV EV EV EV EV LH EH EV SV | SV EH EH LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH LH LH EV EV EV EV LH LH EV EV EV EV EV EV EV EV EV SV | SV LH EH EH EV EV EV EV LH EH EH EV EV EV EV EV EV EV EV SV | SV EH EH LH EV EV EV EV EH EH LH EV EV EV EV EV EV LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		
		//___________________________
		//CHECK IN SOLUTION!!!
//		System.out.println("______________________________________");
		serializer.serialize(grid);
		serializer.serialize(nextGrid);
		//___________________________
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(9, 7);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EV EV EV EV EV EV EV EV EV EH EH EH EH SV | SV LH EH EH EH EV EV EV EV EV EV EV EV EV EV LH EH EH EH SV | SV EH EH EH LH EV EV EV EV EV EV EV EV EV EV EH EH LH EH SV | SV EH EH EH EH EV EV EV EV EV EV EV EV EV EV EV LH EH EV SV | SV EH EH LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH LH LH EV EV EV EV LH LH EV EV EV EV EV EV EV EV EV SV | SV LH EH EH EV EV EV EV LH EV EH EV EV EV EV EV EV EV EV SV | SV EH EH LH EV EV EV EV EH EH LH EV EV EV EV EV EV LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;
		

		grid.uncover(9, 3);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EV EV EV EV EV EV EV EV EV EH EH EH EH SV | SV LH EH EH EH EV EV EV EV EV EV EV EV EV EV LH EH EH EH SV | SV EH EH EH LH EV EV EV EV EV EV EV EV EV EV EH EH LH EH SV | SV EH EH EH EH EV EV EV EV EV EV EV EV EV EV EV LH EH EV SV | SV EH EH LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH LH LH EV EV EV EV LH LH EV EV EV EV EV EV EV EV EV SV | SV LH EH EH EV EV EV EV LH EV EH EV EV EV EV EV EV EV EV SV | SV EH EH LH EV EV EV EV EH EH LH EV EV EV EV EV EV LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;
		

		grid.uncover(6, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EV EV EV EV EV EV EV EV EV EH EH EH EH SV | SV LH EH EH EH EV EV EV EV EV EV EV EV EV EV LH EH EH EH SV | SV EH EH EH LH EV EV EV EV EV EV EV EV EV EV EH EH LH EH SV | SV EH EH EH EH EV EV EV EV EV EV EV EV EV EV EV LH EH EV SV | SV EH EH LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH LH LH EV EV EV EV LH LH EV EV EV EV EV EV EV EV EV SV | SV LH EH EH EV EV EV EV LH EV EH EV EV EV EV EV EV EV EV SV | SV EH EH LH EV EV EV EV EH EH LH EV EV EV EV EV EV LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(4, 4);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EV EV EV EV EV EV EV EV EV EH EH EH EH SV | SV LH EH EH EH EV EV EV EV EV EV EV EV EV EV LH EH EH EH SV | SV EH EH EH LH EV EV EV EV EV EV EV EV EV EV EH EH LH EH SV | SV EH EH EH EV EV EV EV EV EV EV EV EV EV EV EV LH EH EV SV | SV EH EH LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH LH LH EV EV EV EV LH LH EV EV EV EV EV EV EV EV EV SV | SV LH EH EH EV EV EV EV LH EV EH EV EV EV EV EV EV EV EV SV | SV EH EH LH EV EV EV EV EH EH LH EV EV EV EV EV EV LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;


		grid.uncover(4, 3);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH EH LH EV EV EV EV EV EV EV EV EV EH EH EH EH SV | SV LH EH EH EH EV EV EV EV EV EV EV EV EV EV LH EH EH EH SV | SV EH EH EH CV EV EV EV EV EV EV EV EV EV EV EH EH LH EH SV | SV EH EH EH EV EV EV EV EV EV EV EV EV EV EV EV LH EH EV SV | SV EH EH LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH LH LH EV EV EV EV LH LH EV EV EV EV EV EV EV EV EV SV | SV LH EH EH EV EV EV EV LH EV EH EV EV EV EV EV EV EV EV SV | SV EH EH LH EV EV EV EV EH EH LH EV EV EV EV EV EV LH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		
		//___________________________
				//CHECK IN SOLUTION!!!
//				System.out.println("hello______________________________________");
				serializer.serialize(grid);
				serializer.serialize(nextGrid);
				//___________________________
		assertEquals(nextGrid, grid);
		assertTrue(grid.gameOver());
		assertTrue(grid.hasLost());
	}
	
//
	@Test
	void testFullGame() {
		Grid grid;
		Grid nextGrid;
		GridSerializer serializer = new GridSerializer();
		
		String str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LH EH EH EH LH EH LH EH EH LH EH LH EH EH EH SV | SV EH EH EH LH EH EH EH EH EH EH EH EH EH EH EH EH EH EH SV | SV LH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH SV | SV EH EH EH EH EH EH EH EH EH EH LH EH EH EH EH EH EH EH SV | SV LH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH SV | SV EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH SV | SV EH EH EH EH EH EH EH EH EH EH EH EH EH EH EH LH EH EH SV | SV LH EH EH EH EH EH EH EH EH EH EH EH EH EH LH LH EH EH SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		grid = serializer.deserialize(str);

		grid.uncover(7, 4);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LH EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EH EH LH EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EH EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;


		grid.toggleFlag(4, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LH EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EH EH LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EH EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(4, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EH EH LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EH EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(3, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EH EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EH EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(3, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EH EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EH EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(2, 3);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EH EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(2, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EH LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(3, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EH EH EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EH EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(2, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(1, 3);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(1, 4);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(1, 5);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;
	
		grid.uncover(1, 6);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EH EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(1, 7);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LH EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(1, 8);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LH EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(11, 4);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EH EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(11, 3);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EH LH EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(16, 7);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EH LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LH LH EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(16, 8);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EH LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LH LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(15, 7);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LH LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(15, 7);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LH LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(15, 8);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LH EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(15, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EH LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(14, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LH EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(13, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LH EH LH EH EH LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.toggleFlag(8, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EH LH EH EH LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(9, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LH EH EH LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(12, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LH EH EV LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EH EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(12, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LH EH EV LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EH EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(11, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LH EH EV LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EV EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(11, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LH EV EV LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EV EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;


		grid.uncover(11, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LH EV EV LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EH EV EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;

		grid.uncover(10, 2);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LH EV EV LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		assertEquals(nextGrid, grid);
		assertFalse(grid.gameOver());
		grid = nextGrid;
		
		

		grid.toggleFlag(10, 1);
		str = "SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | SV EV EV EV LF EV EV EV LF EV LF EV EV LF EV LF EV EV EV SV | SV EV EV EV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV LF EV EV EV EV EV EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV SV | SV EV EV EV EV EV EV EV EV EV EV EV EV EV EV EV LF EV EV SV | SV LF EV EV EV EV EV EV EV EV EV EV EV EV EV LF LF EV EV SV | SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV SV | ";
		nextGrid = serializer.deserialize(str);
		
//		//___________________________
//		//CHECK IN SOLUTION!!!
//		System.out.println("hello______________________________________");
		serializer.serialize(grid);
//		serializer.serialize(nextGrid);
//		//___________________________
		
		assertEquals(nextGrid, grid);
//		assertTrue(grid.gameOver());
		assertTrue(grid.hasWon());
	}

}
